using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Data;
using System.Web.UI.WebControls;


public partial class Lista_Dinamica : System.Web.UI.Page
{
    string list;
    protected void Page_Load(object sender, EventArgs e)
    {
        dataTable.AutoGenerateColumns = true;
        list = Request.QueryString["Lista"];
        switch (list)
        {
            case "CASOS":
                dataTable.DataSourceID = sqlCases.ID;
                break;
            case "PAQUETES":
                dataTable.DataSourceID = sqlPackets.ID;
                break;
            case "DETALLES":
                dataTable.DataSourceID = sqlCaseDetail.ID;
                break;
        }
        dataTable.DataBind();
        dataTable.AutoGenerateDeleteButton = true;
        dataTable.AutoGenerateEditButton = true;
        dataTable.AutoGenerateSelectButton = true;
    }

    protected void btnBack_Click(object sender, ImageClickEventArgs e)
    {
        switch (list)
        {
            case "CASOS":
                Response.Redirect("Casos.aspx");
                break;
            case "PAQUETES":
                Response.Redirect("Paquetes.aspx");
                break;
            case "DETALLES":
                Response.Redirect("DetallesDeCaso.aspx");
                break;
        }
    }

    /*protected void dataTable_SelectedIndexChanged(object sender, GridViewSelectEventArgs e)
    {
        switch (list)
        {
            case "CASOS":
                Response.Write("Selected=");
                break;
            case "PAQUETES":
                
                break;
            case "DETALLES":
                
                break;
        }
        dataTable.AutoGenerateColumns = true;
        dataTable.DataBind();
        dataTable.AutoGenerateDeleteButton = true;
        dataTable.AutoGenerateEditButton = true;
        
        dataTable.AutoGenerateSelectButton = true;
    }*/

    protected void dataTable_SelectedIndexChanged(object sender, EventArgs e)
    {
        dataTable.AutoGenerateColumns = true;
        switch (list)
        {
            case "CASOS":
                sqlAuxiliar.SelectParameters.Clear();
                sqlAuxiliar.SelectParameters.Add("CAS_ID", dataTable.Rows[dataTable.SelectedIndex].Cells[1].Text);
                dataTable.DataSourceID = sqlAuxiliar.ID;
                break;
            case "PAQUETES":
                sqlAuxiliar2.SelectParameters.Clear();
                sqlAuxiliar2.SelectParameters.Add("PAQ_ID", dataTable.Rows[dataTable.SelectedIndex].Cells[1].Text);
                dataTable.DataSourceID = sqlAuxiliar2.ID;
                break;
            case "DETALLES":
                break;
        }
        dataTable.DataBind();
        dataTable.AutoGenerateDeleteButton = true;
        dataTable.AutoGenerateEditButton = true;
        dataTable.AutoGenerateSelectButton = true;
    }

    protected void btnSearch_Click(object sender, ImageClickEventArgs e)
    {

    }
}